language: php
buildCommands:
  - echo "Installing PostgreSQL extensions..."
  - apt-get update
  - apt-get install -y libpq-dev
  - docker-php-ext-install pdo_pgsql pgsql
  - echo "PostgreSQL extensions installed successfully" 