events {
    worker_connections 1024;
}

http {
    client_max_body_size 100m;
    
    # 確保所有 location 都繼承這個設定
    location / {
        client_max_body_size 100m;
        try_files $uri $uri/ /index.php?$query_string;
    }
    
    location ~ \.php$ {
        client_max_body_size 100m;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
